version: '3'
services:
  web_run:
    image: warning-service/web
    build:
      context: ./
      dockerfile: deploy/web.dockerfile
    ports: 
      # - "9922:22"
      - "8001:8001"
      - "8002:8000"
      - "8888:8888"
      
      # - "8001:8001"
      # - "8888:8888"
      
    volumes:
      - ./backend/:/app/
    command: bash -c "adev runserver api.py" 
    networks:
      emergencyservice_dev: # чтобы наш хостовый nginx мог достучаться по общей с прокси сети до других контейнеров в той же сети
        aliases:
          - api.run.dev
networks: 
  emergencyservice_dev:
    external: true

