version: '3'
services:
  web:
    image: warning-service/web
    build:
      context: ./
      dockerfile: deploy/web.dockerfile
    ports: 
      # - "9922:22"
      - "8000:8000"
      # - "8001:8001"
      # - "8888:8888"
      
    volumes:
      - ./backend/:/app/
#    command: bash -c "adev runserver api.py" 
    # depends_on:
    #   - mongo
    networks:
       emergencyservice_dev: # чтобы наш хостовый nginx мог достучаться по общей с прокси сети до других контейнеров в той же сети
           aliases:
               - api.dev
networks: 
  emergencyservice_dev:
    external: true

