version: '3'
services:
#   web:
#     image: warning-service/web
#     build:
#       context: ./
#       dockerfile: deploy/web.dockerfile
#     ports: 
#       - "9922:22"
#       - "8000:8000"
#       - "8001:8001"
#       - "8888:8888"
      
#     volumes:
#       - ./backend/:/app/
# #    command: bash -c "adev runserver api.py" 
#     depends_on:
#       - mongo
#     network_mode: "host"

  mongo:
    image: mongo
    ports:
    - "27017:27017"

  

  front:
    image: warning-service/front
    build:
      context: ./
      dockerfile: deploy/front.dockerfile
    volumes:
      - ./frontend/:/app/
      - /app/node_modules              
      # - node_modules:/app/node_modules        
    ports:
      - "8080:8080"
    command:  npm run dev  # sleep infinity
      # environment:
        # - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432
        # Making production the default.
        # - QUIZ_ENV=production
    # db:
    #   image: postgres:10.2-alpine
    #   environment:
    #     - POSTGRES_USER=postgres
    #     - POSTGRES_PASSWORD=postgres
# volumes:
#         node_modules:
#           driver_opts:
#            type: none
#            device:  ${PWD}/frontend/node_modules
#            o: bind
